# Generated by Django 3.0.5 on 2020-04-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='School Name')),
                ('email', models.EmailField(max_length=254, verbose_name='School Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='School Address')),
                ('school_start_time', models.TimeField(verbose_name='School Start Time')),
                ('school_end_time', models.TimeField(verbose_name='School End Time')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
            options={
                'verbose_name': 'School Profile',
                'ordering': ('name',),
            },
        ),
    ]
