# Generated by Django 3.0.5 on 2020-05-11 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField(verbose_name='Academic Year')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ('academic_year',),
            },
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Allergies')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Allergies',
                'verbose_name_plural': 'Allergies',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Chronic_Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Chronic Diseases')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chronic Disease',
                'verbose_name_plural': 'Chronic Diseases',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=500, verbose_name='Class Code')),
                ('description', models.CharField(max_length=500, verbose_name='Class Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Class Description',
                'verbose_name_plural': 'Classes Description',
                'ordering': ('class_code',),
            },
        ),
        migrations.CreateModel(
            name='Communication_Methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Preferred Communication Method')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Preferred Communication Method',
                'verbose_name_plural': 'Preferred Communication Methods',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Countries')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Designation')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Education_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Education Type')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Education Type',
                'verbose_name_plural': 'Education Types',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Ethnics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Ethnics')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ethnic',
                'verbose_name_plural': 'Ethnics',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Family_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Family Status')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Family Status',
                'verbose_name_plural': 'Family Status',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Gender')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=5, verbose_name='Grade Code')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Grade Level')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ('grade_code',),
            },
        ),
        migrations.CreateModel(
            name='Highest_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Highest Grade')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Highest Grade',
                'verbose_name_plural': 'Highest Grades',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='ID_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='ID Types')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ID Type',
                'verbose_name_plural': 'ID Types',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Home Language')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Language_Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Language Preference')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language Preference',
                'verbose_name_plural': 'Language Preferences',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Main_Relationships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Relationships')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Marital_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Marital Status')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Status',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Medical_Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Medical Aid Name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medical Aid',
                'verbose_name_plural': 'Medical Aid',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Nationality')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Occupation')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupation',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Occupation_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Occupation Status')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Occupation Status',
                'verbose_name_plural': 'Occupation Status',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Parent_Deceased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Parent Deceased')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parent Deceased',
                'verbose_name_plural': 'Parents Deceased',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Parent_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Parent Types')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parent Type',
                'verbose_name_plural': 'Parent Types',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Provinces')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Qualification')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Reasons_For_Leaving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Reason For Leaving')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reason For Leaving',
                'verbose_name_plural': 'Reasons For Leaving',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Religion')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religions',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ('term',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(max_length=50, verbose_name='Fee Code')),
                ('fee_description', models.CharField(max_length=500, verbose_name='Fees Description')),
                ('fee_amount', models.FloatField(verbose_name='Fees Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.AcademicYear', verbose_name='Academic Year')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.GradeLevel', verbose_name='Grade Level')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'School Fees',
                'verbose_name_plural': 'School Fees',
                'ordering': ('fee_code',),
            },
        ),
    ]
