# Generated by Django 3.0.5 on 2020-04-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20200418_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
