# Generated by Django 3.0.5 on 2020-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0003_delete_schoolprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Designation')),
            ],
            options={
                'verbose_name': 'Designation',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Gender',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Home Language')),
            ],
            options={
                'verbose_name': 'Language',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Marital_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Marital Status')),
            ],
            options={
                'verbose_name': 'Marital Status',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'Nationality',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Nationality')),
            ],
            options={
                'verbose_name': 'Qualification',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Religion')),
            ],
            options={
                'verbose_name': 'Religion',
                'ordering': ('description',),
            },
        ),
    ]
