# Generated by Django 3.0.5 on 2020-04-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_designation_gender_language_marital_status_nationality_qualification_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ('description',), 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ('description',), 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ('description',), 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='marital_status',
            options={'ordering': ('description',), 'verbose_name': 'Marital Status', 'verbose_name_plural': 'Marital Status'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ('description',), 'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ('description',), 'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
        migrations.AlterModelOptions(
            name='religion',
            options={'ordering': ('description',), 'verbose_name': 'Religion', 'verbose_name_plural': 'Religions'},
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Qualification'),
        ),
    ]
