# Generated by Django 3.0.5 on 2020-04-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacherprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
