# Generated by Django 3.0.5 on 2020-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_number',
            field=models.IntegerField(blank=True, default='57660822', editable=False, unique=True, verbose_name='Employee Number'),
        ),
    ]
