# Generated by Django 3.0.5 on 2020-05-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_auto_20200512_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parents',
            options={'ordering': ('p_id',), 'verbose_name': 'Parent Profile', 'verbose_name_plural': 'Parents Profile'},
        ),
        migrations.AddField(
            model_name='parents',
            name='p_id',
            field=models.CharField(blank=True, editable=False, max_length=1024, unique=True, verbose_name='Parent ID'),
        ),
    ]
